declare let BUILD_TARGET: 'wx' | 'my' | 'swan' | 'qq' | 'tt' | 'ks' | 'xhs';
declare let wx: any;
declare let my: any;
declare let swan: any;
declare let tt: any;
declare let xhs: any;
declare let qq: any;
declare let ks: any;
declare let __wxConfig: any;
declare let __qqConfig: any;
declare let __appxStartupParams: any;
